### PR TITLE
Fixed a bug causing "Mean of empty slice" warnings during pYAAPT execution

### PR DESCRIPTION
**Pull request by omaraltayyan**
the bug is discussed in #6 (comments 9 through 12) and this code seems to fix it, i ran the tests after the modifications and everything seems to work well.

### CODE REVIEW

**Comment by omaraltayyan** [comment]
hi @bjbschmitt

i made a fix for the bug we discussed in #6 earlier, hope you find it good enough.

**Comment by omaraltayyan** [comment]
@bjbschmitt I've just tested the algorithm on my entire dataset, which is about 14000 files totaling 56 hours, and there weren't any errors thrown as before.

**Comment by bjbschmitt** [comment]
Hi @omaraltayyan I ran your script and I was finally able to reproduce the bug. It seems that the issue occurs when you create a `SignalObj` instance using a PCM signal as input data (the output of the `scipy.io.wav.read()` function is PCM). 

Your solution works fine, but there is a problem: if you want now to create a `SignalObj` instance using an input float signal (for example, an output coming from another process or source), the pcm2float function will raise an error. So, I added an extra "if" before pcm2float in order to check whether the signal is PCM or float. By doing this, the `SignalObj` instances can be created with either PCM and float inputs.

Here is the script that you sent me with a small modification (line 19) 
[empty_slice.py.zip](https://github.com/bjbschmitt/AMFM_decompy/files/2177783/empty_slice.py.zip)
. If you run it using your solution, it raises the error and you won't be able to use input float signals.

I'll commit then your code, make some modifications and update the package soon. Thanks again for your help!

**Comment by omaraltayyan** [comment]
@bjbschmitt thanks a lot

i don't know if you have noticed or not but i also modified the PCM2float function so it doesn't run unless the type is int, by the way no error gets raised by the script you modified.

Thanks again for your efforts

**Comment by omaraltayyan** [comment]
@bjbschmitt i checked your modifications and i understand the problem

Thanks again.

**Comment by bjbschmitt** [comment]
Ok cool, I guess that the old commentaries in the code were not very good anyway, so I'm modifying them to make things more clearer.

**Comment by omaraltayyan** [comment]
Ok great
Thanks again and good luck with your work.

**Pull request merged**
